### ISSUE TITLE
Some pages fail to complete the test when there are requests without responses

### ISSUE THREAD

**Issue by adamread** [gtech-professional-services/tagspeed_audit#66]
## Expected Behavior
Most pages should run through the entire test without error.

## Actual Behavior
Some requests do not have a response. When this happens, the entire test is cancelled.

## Steps to Reproduce the Problem

1. Find a url where there are requests made but no response is made (e.g. https://aftonbladet.se)
1. Run a test.

## Notes
In devtools, it looks like there is a response made to the request. Using the `response` method returns a null though.

**Comment by adamread** [comment]
The aftonbladet example has headers, but not a content-type.

**Comment by nenuadrian** [comment]
Interesting! Will have a look

**Comment by adamread** [comment]
Seems to be fixed with last merge.
